name: module3_task2
on:
  push:
    tags:
      - '1.0.0'
  schedule:
    - cron: '0 0 * * *'
name: module3_task3
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: cd module3_task1 && ./setup.sh
      - run: cd module3_task1 && make help
      - run: cd module3_task1 && make clean
      - run: cd module3_task2 && make validate
      - run: cd module3_task2 && make lint
      - run: cd module3_task2 && make package
      - if: startsWith(github.ref, 'refs/tags/')
        name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: '${{ github.ref }}'
          files: |
            ./module3_task3/awesome-website.zip
          body: |
            $(cat ./module3_task3/DEPLOY.md)
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v2
        with:
          name: awesome-website
          path: ./module3_task3/awesome-website.zip
