---
name: module4_task4
on:
  push:
  pull_request:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build-artifact:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: cd module4_task4 && make build-docker
      - run: cd module4_task4 && make build
      - run: cd module4_task4 && make unit-tests
      - run: cd module4_task4 && make integration-tests
      - run: cd module4_task4 && make validate
      - run: cd module4_task4 && make help
      - run: cd module4_task4 && make lint
      - run: cd module4_task4 && make package
      - run: cd module4_task4 && make docker-tests
      - uses: actions/upload-artifact@v3
        with:
          name: awesome-website
          path: ./module4_task4/awesome-website.zip
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name:
          heroku_email:
          usedocker: true
