name: Module3_Task0

on:
  push:
    branches: [ main ]
  schedule:
    - cron: '30 22 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - run: cd module3_Task0 && make help
