name: release-drafter
on:
  push:
    branches:
      - main
jobs:
  release-drafter:
    runs-on: ubuntu-22.04
    steps:
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          name: awesome-website.zip
          path: ./module3_task3/awesome-website.zip
      - name: Upload Release
        uses: release-drafter/release-drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          with:
          tag_name: ${{ github.ref }}
          name: DEPLOY.md
          path: ./module3_task3/DEPLOY.md
